version: '3.8'
services:
  jsight-server:
    image: jsight/jsight-server:5.0
    environment:
      - JSIGHT_SERVER_CORS=true
      - JSIGHT_SERVER_STATISTICS
    ports:
      - '${SERVER_HOST_PORT}:8080'

